library(rtweet)
library(openxlsx)

tw_token <- create_token(
  app = "rafaela_CPOP",
  consumer_key = "0JBFJGv2D4wgBqmOv7GYo3yP7",
  consumer_secret = "7hEmxJWMxsILsDrfNPNI7DQP5Mq05Q9JKttfOCsTXu6BR632RP",
  access_token = "1016753287914237952-zk3LEM4P2f9Hxpa9ZfSDHBvJnI7P9U",
  access_secret = "miLtS5qbJaRHryhsfN3dHNEEstSWiBGGxHkGDAYWs6U79"
)

bd_deputados <- get_timelines(user = c("AcacioFavacho", "adriventurasp", 
                                       "adrianodobaldy", "AecioNeves", "AfonsoFlorence",
                                       "DepAfonsoHamm", "afonso_motta", "depaguinaldo11",
                                       "FaleiroAirton", "Alan_Rick", 
                                       "Alceu_Moreira", "alesilva_38", "AlencarBraga13",
                                       "alessandromolon", "AlexManente23", "depalexsantana",
                                       "77_frota", "lexandreleite", "padilhando", "AleSerfiotis",
                                       "AlexisFonteyne", "Alice_Portugal", "alielmachado",
                                       "dep_alinegurgel", "AlineSleutjes", "Altineu",
                                       "aluisiomendesma", "amaronetotv", "Andredepaula55",
                                       "aferreira2020", "andrepdt12", "DepAndreFufuca",
                                       "AndreJanonesAdv", "DeputadaAngela", "depchinaglia",
                                       "ArnaldoJardim", "aroldomartins", "ArthurLira_",
                                       "DepArthurMaia", "deputadoatila", "dep_acoutinho",
                                       "aureacarolinax", "AureoRibeiroRJ", "DeputadoBacelar",
                                       "Baleia_Rossi", "dasilvabenedita", "benesleocadiorn",
                                       "BetoFaroPT", "betopereirams", "BetoRosado", "BiaCavassa",
                                       "Biakicis", "bibonunes1", "BiradoPindare", "BocaAbertaOf",
                                       "BohnGass", "BoscoCosta_SE", "boscosaraiva", "jrbozzella",
                                       "DepBrunaFurlan", "CacaLeao", "CamiloPSB", "capalbertoneto",
                                       "capitaoaugusto_", "fabioabreuofc", "carladicksonrn",
                                       "CarlaZambelli38", "carloschiodini", "Carlos_Gaguim", 
                                       "carlosgomesdep", "carlosjordy", "carlossampaio_", 
                                       "carlosveraspt", "CarlosZarattini", "carmen_zanotto",
                                       "CarolDeToni", "cassio_40", "CelioMouraTO", "CelioStudart",
                                       "maldaner_celso", "celsorussomanno", "depcelsosabino",
                                       "cezinhamadurei1", "CharlesFederal", "charllesevg",
                                       "chico_dangelo", "BrazaoChiquinho", "ToniettoChris",
                                       "ChristianeYared", "christinoaureo", "dep_clarissa",
                                       "deputadocajado", "cel_armando", "DepChrisostomo",
                                       "CoronelTadeu", "depdavitoria", "depdagoberto", "Drdamiaof",
                                       "Daniel_PCdoB", "DanielCoelho23", "DFDanielFreitas",
                                       "TrzeciakDaniel", "DanielaWaguinho", "danilocabralpe",
                                       "davidmirandario", "davidbrsoares", "DelegadoFurtado", 
                                       "EderMauroPA", "DelegadoFreitas", "DelegadoPablo_",
                                       "denisbezerra", "diegogarciapr", "DomingosSavioMG",
                                       "DrFredericoMG", "jaziel_dr", "DrLeonardomt",
                                       "Doutorluizinhot", "drluizovando", "zachariascalil",
                                       "DraManato", "EdilazioJunior_", "ediolopes", "EdmilsonPSOL",
                                       "ednahenriquedep", "eduardobarbosa_", "eduardobismarck",
                                       "BolsonaroSP", "EduardoBraide", "Eduardo_Cury", 
                                       "eduardodafonte", "efraimfilho", "elcionebarbalh0",
                                       "elidiasborges", "EliasVazGyn", "ElmarNascimento",
                                       "emanuelzinhomt", "enioverri", "enricomisasi", "erikakokay",
                                       "erosbiondini", "EuclydesPetter", "EvairdeMelo", "roman_evandro",
                                       "FabioHenriqueSE", "depfmitidieri", "deputadofabiomg",
                                       "fabioreis_se", "fabio_schiochet", "f_trad", "DepFaustoPinato",
                                       "FederalFelicio", "felipecarreras", "FFrancischini_",
                                       "rigoni_felipe", "FelixMendoncaJr", "fernandapsol", 
                                       "fernandofilhope", "fmonteiroPE", "depfernandor","filipebarrost",
                                       "FlaviaArrudaDF", "FlviaMo74599829", "flavionpi", "flordelismk",
                                       "franciscojr_go", "FrancoCartafina", "FredCostaDep",
                                       "freianastaciopt", "GelsonAzevedoRJ", "GelsonAzevedo_",
                                       "DepGenecias", "GeneralGirao", "GenPeternelli", "geninhozuliani",
                                       "geovaniadesa", "gervasiomaia", "fernandogiacobo", "gilcutrim",
                                       "gilbertoabramo", "gnascimento20", "gilson__marques", 
                                       "giovanicherini", "GiovaniFeltes", "Glauber_Braga", 
                                       "glaustindafokus", "gleisi", "greyceelias", "GuigaPeixotoSP",
                                       "capitaoderrite", "GuilhermeMussi", "depgurgel", "gustavofruet",
                                       "GustinhoRibeiro", "_GutembergReis", "deputadoharoldo", 
                                       "HeitorFreireCE", "HeitorSchuch", "heldersalomao", "heliocosta_sc",
                                       "depheliolopes", "HenriqueFontana", "herciliodiniz", 
                                       "herculanopassos", "RochaHildorocha", "drhiran_", "depHugoLeal",
                                       "HugoMottaPB", "IdilvanAlencar", "deputadokannar1", 
                                       "oficialigortimo", "iracemaportela", "bulhoesjr", "IvanValente",
                                       "jandira_feghali", "jqcassol", "DepJefferson", "jeronimogoergen",
                                       "jesussergioac", "JHC_40", "jhonatan_djesus", "joaocamposdep",
                                       "DeputadoBacelar", "depjoaodanielpt", "JoaoCampos", "dep_joaomarcelo",
                                       "joaoromaneto", "depjpassarinho", "JoeniaWapichana", "joicehasselmann",
                                       "Jorge_Braz", "GoettenJorge", "depjorgesolla", "JoseAirtonPT",
                                       "guimaraes13PT", "ZeMarioGO", "depjosenelto", "Priante15", "ZeRicardoAM",
                                       "dep_joserocha", "joseildoramos", "josimarPL22", "Juarezcostamt",
                                       "JulianLemosopb1", "DepJulioCesarPI", "JulioCesarRib", "depjuliodelgado",
                                       "JuninhodoPneu", "cabojunioamaral", "juniorferrari55", "JuniorManoDep",
                                       "DepJuscelino", "LaercioFederal", "lafayetteandrad", "laurietecantora",
                                       "deputadaleandre", "DepLeoMoraes", "leomotta_ofc", "depleomonteiro",
                                       "joseleonidas", "LeurLomantoJr", "lidicedamata", "lincoln_portela",
                                       "LizianeBayer", "LTrutis", "LourivalGomesrj", "lucasvgonzalez",
                                       "LucasRedecker", "LucasVergilioGO", "bivaroficial", "LucianoDucci",
                                       "LuisMirandaUSA", "LuisTibeOficial", "luisa_canziani", "depluizantonio",
                                       "DepLuizCarlos", "deputadomotta", "Oficialluizlima", "LuizNishimori",
                                       "lpbragancabr", "luizaerundina", "luizaogoulart", "LuizianneLinsPT", 
                                       "MofattoMagda", "majorfabianadep", "soumara15", "marcelvanhattem", 
                                       "marceloaro", "Marcelobrumdep", "caleromarcelo", "MarceloFreixo", 
                                       "marceloramosam", "marciobiolchi", "marciojerry", "dpmarciomarinho", 
                                       "MarcoBertaiolli", "Maubmarcon", "MarcosA_Sampaio", "marcospereira04", 
                                       "MargaretCoelho", "JFMargarida", "mariadorosario", "mariarosassp", 
                                       "DeputadaMariana", "MariliaArraes", "dramarinapi", "mario_heringer", 
                                       "JrNegromonte", "depmarrecafilho", "marxbeltrao", "DepMauricioRS", 
                                       "mauro_bfilho", "nazif_dr", "MerlongSolano", "DMiguellombardi", 
                                       "MiltonVieiraOfc", "VarellaMisael", "DepFederalMoses", "natbonavides", 
                                       "nelsonbarbudo", "nereucrispim", "geller_neri", "newton1510", "depnicoletti", 
                                       "StainsackNilson", "DepNilsonPinto", "NiltoTatto", "NivaldoAlbuq", 
                                       "normaayub11", "odaircunhamg", "OLIVALMARQUES", "orlandosilva", 
                                       "deposiresdamaso", "OsmarTerra", "OssesioSilva", "OtoniDepFederal", 
                                       "OttoAlencarFilh", "dep_padrejoao", "pastorgil_", "prisidorio", 
                                       "Patrus_Ananias", "paulambelmonte", "paulaodopt", "pauloabiackel", 
                                       "PauloAzi", "PauloBengtson", "PauloMartins10", "DF_PauloFreire", 
                                       "pauloganime", "deppauloguedes", "dep_paulinho", "deputadofederal", 
                                       "deppauloramos", "pauloteixeira13", "PedroABezerra", "pedroocl", 
                                       "depPedroLucasF", "pedro_lupion", "pedropaulo", "uczai", "pedrowestphalen",
                                       "perpetua_acre", "pinheirinhomg", "PompeodeMattos", "KatiaSastre",
                                       "marcofeliciano", "ProfIsrael", "professorjoziel", "deppimentel",
                                       "profdorinha", "profmarcivania", "prof_rosaneide", "RafaelMottaRN",
                                       "raimundocostaba", "RaulHenry", "ReginaldoLopes", "stephanesjunior",
                                       "rejane_dias", "RenatoAQueiroz", "renildo", "RicardoBarrosPP",
                                       "ricardozguidi", "RicardoIzar", "ricardosilva", "RobertoAlves_10",
                                       "robertodelucena", "segueoRP", "rodrigoagost", "coelho_rodrigo",
                                       "MGRodrigoCastro", "RodrigoMaia", "RogerioCorreia_", "roman_evandro",
                                       "ronaldocarletto", "10ronaldomartin", "DepRosanaValle", "rosangelasgomes",
                                       "rosemodestoms", "23rubensbueno", "RubensOtoni", "rubenspereirajr",
                                       "rfalcao13", "ruycarneiropb", "samiabomfim", "samuelmoreira", "DepSanderson",
                                       "santini_ronaldo", "SargentoFAHUR", "Schiavinato_", "_sergiosouza",
                                       "vidigalsergio", "severinopessoaa", "sidneyleite_", "silascamara_",
                                       "silviacristinax", "Silvio_CFilho", "depsorayasantos", "DepSostenes",
                                       "depstefano", "subgonzagamg", "tabataamaralsp", "TadeuAlencarPE", 
                                       "filippellireal", "taliriapetrone", "tedcontioficial", "terezanelmaal", 
                                       "tiago_dimas", "TiagoMitraud", "tiriricanaweb", "deputadotoninho", 
                                       "tuliogadelha", "ValdevanNoventa", "DepValmir", "vanderloubet", 
                                       "vanderleimacris", "vavamartinspa", "depvermelho", "VICENTINHOPT", 
                                       "vicentinhojr", "Vilsondafetaemg", "falecomvinicius", "VinciusGurgel3",
                                       "ViniciusPoit", "MajorVitorHugo", "DepVitorLippi", "WaldenorPereira", 
                                       "walteralvesrn", "pradoweliton", "WilsonSantiago_", "WladGarotinho",
                                       "WolneyQueirozM", "Dep_ZeCarlosPT", "ZeMarioGO", "depzeneto1323",
                                       "ZeSilva_", "zeca_dirceu"),
                        n = 3200,
                        token = tw_token)

write.xlsx(bd_deputados, "C:/Users/rafas/OneDrive/Área de Trabalho/Doutorado/Tese/Bancos")

  bd_senadores <- get_timelines(user = c("senadoraeliane", "JaymeSenador", "ZequinhaMarinho",
                                     "PlinioValerio45", "LucasBarreto_AP", "MailzaGomes",
                                     "ContaratoSenado", "Jarbas156", "SenStyvenson", "zenaidern", 
                                     "EduGiraoOficial", "Sen_Oriovisto", "leiladovolei", "asilveiramg", 
                                     "angelocoronel_", "rodrigopacheco", "_AlessandroSE", "SorayaThronicke",
                                     "SenadoraRose", "davialcolumbre", "senadorpaulor", "simonetebetbr", 
                                     "OmarAzizSenador", "ottoalencar", "renancalheiros", "carlosfportinho", 
                                     "RobertoRocha_MA", "telmariomotarr", "soudaniellapb", "irajasenador", 
                                     "nildagondimpb", "lasiermartins", "SenadorKajuru", "esperidiaoamin_", 
                                     "_luizdocarmo", "elmanoferrer", "EduardoBraga_AM", "Vanderlan_VC", 
                                     "MarcosRogerio", "SenadorRogerio", "Carloshbfavaro", "tassojereissati",
                                     "MarceloCastroPI", "meciasdejesus", "elizianegama", "EduardoGomesTO", 
                                     "marciombittar", "senadorpetecao", "wevertonrocha", "randolfeap", 
                                     "IzalciLucas", "senadorhumberto", "carlosaviana", "alvarodias_", 
                                     "sen_wellington", "acirgurgacz", "jose_anibal", "jaqueswagner", 
                                     "confuciomoura", "jader_barbalho", "Heinzeoficial", "venezianovital", 
                                     "marcosdoval", "nelsinhotrad", "fbezerracoelho", "jorginhomello", 
                                     "senadorcidgomes", "Collor", "RomarioOnze", "FlavioBolsonaro", 
                                     "paulopaim", "RodrigoCunhaAL", "Reguffe", "joseserra_", "darioberger", 
                                     "KatiaAbreu", "maragabrilli", "jeanpaulprates"), 
                            n = 3200,
                            token = tw_token)

write.xlsx(bd_senadores, "C:/Users/rafas/OneDrive/Área de Trabalho/Doutorado/Tese/Bancos")

